name = "Scheduler"
uuid = "e66378d9-a322-4933-8764-0ce0bcab4993"
authors = ["Five Grant <5@fivegrant.com>"]
version = "0.2.0"

[deps]
AlgebraicPetri = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
EasyModelAnalysis = "ef4b24a4-a090-4686-a932-e7e56a5a83bd"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONTables = "b9914132-a727-11e9-1322-f18e41205b0b"
JobSchedulers = "eeff360b-c02d-44d3-ab26-4013c616a17e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Pipelines = "ef544631-5c6f-4e9b-994c-12e7a4cd724c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
